import { useState, useEffect } from "react";
import { ApolloClient, InMemoryCache, ApolloLink, gql } from "@apollo/client";
import { YogaLink } from "@graphql-yoga/apollo-link";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: new YogaLink({
    endpoint: "/api/graphql",
  })
});

export default function Home() {
  const [greeting, setGreeting] = useState(null);
  const [notification, setNotification] = useState(null);

  useEffect(() => {
    client
      .query({
        query: gql`
        query {
          hello
        }`
      })
      .then((res) => setGreeting(res.data.hello))
      .catch((err) => console.log(err));
  }, [greeting]);

  client.subscribe({
    query: gql`
    subscription {
      notification
    }`
  }).subscribe({
    next: ({ data }) => setNotification(data.notification)
  });


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{greeting || "Loading..."}</h1>
        {notification && <p className={styles.description}>{notification}</p>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
